Eng 3854 mask
Basis-Theory/basistheory-ios pull request #9
Opened 2022-11-25 13:48 UTC by lcschy

## Description

-

## Testing required outside of automated testing?

- [ ] Not Applicable

### Screenshots (if appropriate):

- [ ] Not Applicable

## Rollback / Rollforward Procedure

- [ ] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2022-11-26 15:56 UTC, brigonzalez requested changes
nice work! just a few concerns here

2022-11-26 15:56 UTC, brigonzalez commented on BasisTheoryElements/Sources/BasisTheoryElements/CardVerificationCodeElementUITextField.swift
> +    public override var validation: ((String?) -> Bool)? {
allowing `validation` to be publicly set means the user can see the plaintext value that’s set within a textfield since we pass in the plaintext value as the arg for that function. we need to have a discussion as a bigger group before allowing this

```suggestion
    override var validation: ((String?) -> Bool)? {
```

2022-11-26 15:56 UTC, brigonzalez commented on BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
> +    public var validation: ((String?) -> Bool)?
```suggestion
    var validation: ((String?) -> Bool)?
```

2022-11-26 15:56 UTC, brigonzalez commented on BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
> +            if (super.text!.count != inputMask!.count ) {
that `super.text!` doesn’t cause problems here? can `super.text` ever be `nil` here?

2022-11-26 15:56 UTC, brigonzalez commented on BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
> +            guard previousValue == super.text else {
we only want to emit an event and continue with this function if we didn’t change the text with a mask? I think we still want the rest of this function to run when we’ve applied a mask

2022-11-26 15:56 UTC, brigonzalez commented on BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
> +            let maskedChar = getMaskedChar(char: String(char), maskValue: maskValue)
looks like this line can move under line 58 since it’s only used in that condition

2022-11-26 15:56 UTC, brigonzalez commented on BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
> +                    maskedText =  maskedText + (maskValue as! String) + nextMaskedChar
does this work with a mask that has any 2 consecutive strings? I can’t think of a mask that has that but I’m not sure this would work in that case

2022-11-26 16:01 UTC, brigonzalez commented on BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
> +            guard previousValue == super.text else {
ah never mind! I see why you did this!

2022-11-28 12:55 UTC, lcschy commented on BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
> +            guard previousValue == super.text else {
Yep, its so it doesnt emit an event every time you type when the mask is already full.

2022-11-28 13:14 UTC, lcschy commented on BasisTheoryElements/Sources/BasisTheoryElements/CardVerificationCodeElementUITextField.swift
> +    public override var validation: ((String?) -> Bool)? {
Ah good point! I thought it was just missing. 
Initially I thought you didn't need to add `public` so when I couldn't access the mask I thought that was a mistake.
Reverted!

2022-11-28 13:15 UTC, lcschy commented on BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
> +            if (super.text!.count != inputMask!.count ) {
You're right, I got it mixed up w/ the inherited, fixed.

2022-11-28 13:33 UTC, lcschy commented on BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
> +                    maskedText =  maskedText + (maskValue as! String) + nextMaskedChar
You're right it doesn't, I'll try to figure that one out today.
I think most of the difficult is trying to support single/typed input vs pasted w/ the same method.
If I struggle too much I'll just split them, already spent too much time on this.

2022-11-28 17:56 UTC, brigonzalez commented on BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
> +    var inputMask: [(Any)]?
parenthesis is needed around `Any`?

2022-11-28 17:56 UTC, brigonzalez commented on BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
> +                super.text = conformToMask(text: newValue ?? "")
nitpick: I think it's cleaner to allow `conformToMask` to take in `nil` and have that function handle it. it would reduce conditionals

2022-11-28 17:56 UTC, brigonzalez commented on BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
> +    var inputMask: [(Any)]?
I think `inputMask` would be a good addition to the `InternalElementProtocol`. that way we can see that `mask` is an available option for elements

2022-11-28 17:56 UTC, brigonzalez commented on BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
> +                if String(char) == placeholderChar {
does this break if a user enters `_` in the input?

2022-11-28 21:11 UTC, brigonzalez approved these changes

2022-11-28 21:42 UTC, merged